name: Apply Label to External Pull Requests

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  apply_label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Apply Label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_author=$(gh pr view https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} --json author -q '.author.login')
          author_permission=$(gh api /repos/${{ github.repository }}/${pr_author}/permission -t {{.permission}})

          # If the user can write or is an admin, apply no label
          if [[ $author_permission == "write" || $author_permission == "admin" ]]; then
            echo "Adding 'External' label to the pull request."
            gh pr label ${{ github.event.pull_request.number }} add "External"
          else
            echo "The pull request is opened by a maintainer. No label will be applied."
            gh pr label ${{ github.event.pull_request.number }} add "Internal"
          fi
