name: Apply Label to External Pull Requests

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  apply_label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Apply Label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_author=$(gh pr view https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} --json author -q '.author.login')
          repo_owner=$(gh repo view ${{ github.repository }} --json owner.login -q '.owner.login')

          # Check if the user is a maintainer
          is_maintainer=$(gh api -X GET /repos/${{ github.repository }} -f per_page=100 -f page=1 --json '[.permissions.admin]' -q ".[] | .[\"${pr_author}\"]")

          # If the user is not a maintainer, apply the label
          if [[ $is_maintainer == "null" ]]; then
            echo "Adding 'External' label to the pull request."
            gh pr label ${{ github.event.pull_request.number }} add "External"
          else
            echo "The pull request is opened by a maintainer. No label will be applied."
            gh pr label ${{ github.event.pull_request.number }} add "Internal"
          fi
