name: Apply Label to every Pull Requests

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  apply_label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Apply Label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh pr edit ${{ github.event.pull_request.number }} --add-label "External"
